# Generated by Django 2.2.6 on 2019-11-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191023_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='账号余额'),
        ),
    ]
